AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources: 
  Function: 
    Type: AWS::Serverless::Function 
    Properties: 
      Handler: lambda.handler
      Runtime: ruby2.5 
      Timeout: 30
      FunctionName: kaname-mahiro-ufo
      Role: arn:aws:iam::486414336274:role/kaname-mahiro-ufo
      Environment:
        Variables:
          TABLE: kaname-mahiro
          TZ: Asia/Tokyo
